INCLUDE         += -I../inc/
OBJDIR          += ../libs/

lib-y           += libsockserver.a
library         += libandroidmanage.a 

obj-y           += usbpthread.o
obj-y           += mainthread.o
obj-y           += mutexpthread.o
obj-y           += downthread.o
obj-y           += appthread.o
obj-y           += filethread.o
obj-y           += netthread.o
obj-y           += sockserver.o
obj-y           += amservice.o
obj-y           += sampleclient.o

obj-y           += manage.o
obj-y           += mainthread.o
obj-y           += downthread.o
obj-y           += filethread.o
obj-y           += appthread.o
obj-y           += down.o
obj-y           += file.o
obj-y           += app.o
obj-y           += mms.o
obj-y           += storage.o
obj-y           += book.o
obj-y           += sh_module.o

include ../build/makefile.in
